### ISSUE TITLE
Build an AGL image for AWS Greengrass Core - Perform kernel configurations

### ISSUE THREAD

**Issue by hgflas** [awslabs/aws-iot-framework-for-agl#2]
Hello,

I am currently trying to build an AGL image for AWS Greengrass Core for the raspberrypi3. The referenced tutorial [2] again refers to an external document: "AGL Devkit - Build your 1st AGL Application". 
However, this is designed for the "Porter Board" and not for the RaspberryPi, so I tried to follow this tutorial and modify all the necessary lines.

Step 4 of the tutorial says: "Perform kernel configurations required by AWS Greengrass".
But how can I do that? I can not find instructions, neither in the AGL documentation nor in the AWS documentation.

[2] http://docs.automotivelinux.org/docs/devguides/en/dev/reference/sdk-devkit/docs/part-1/1_0_Abstract.html

Thank you and best regards

**Comment by hnishar** [comment]
You can add the kernel config fragment to the appropriate yocto layer, so it gets picked up by bitbake. I chose to add it to the 'meta-renesas-rcar-gen3' layer since I was building the AGL image for the Renesas R-Car M3 board. I created a new file called 'greengrass.cfg' with the required Kernel options and placed it under meta-rcar-gen3/recipes-kernel/linux/linux-renesas/greengrass.cfg and updated the corresponding recipe to include the 'greengrass.cfg' file (meta-rcar-gen3/recipes-kernel/linux/linux-renesas_4.9.bb)

Hope this helps!

**Comment by hgflas** [comment]
Thank you, that helps me a lot.
However, I have a few more questions.

The file "greengrass.cnf" contains the kernel configuration. That means the listed configurations can easily be copied in and already correspond to the correct syntax?

> "You can add the kernel config fragment to the appropriate yocto layer, so it gets picked up by bitbake. I chose to add it to the 'meta-renesas-rcar-gen3' layer since I was building the AGL image for the Renesas R-Car M3 board"

That means I can add the configuration in meta-raspbarrypi layer and update the recipe in meta-raspbarrypi/recipes-kernel/linux/linux-raspbarrypi_4.9.bb. But how do I add the file "greengrass.cnf" to the recipe? Can you post the updated file?

**Comment by hnishar** [comment]
Yes, you can copy all the kernel settings in "greengrass.cnf" file, which is the first step. 

CONFIG_POSIX_MQUEUE=y
CONFIG_OF_OVERLAY=y
CONFIG_OVERLAY_FS=y
................

Second step is to reference the "greengrass.cnf" file from bitbake recipe (meta-rcar-gen3/recipes-kernel/linux/linux-renesas_4.9.bb)

SRC_URI_append = " \
    file://defconfig \
    file://touch.cfg \
    file://greengrass.cfg \  
    ${@base_conditional("USE_AVB", "1", " file://usb-video-class.cfg", "", d)} \
"

**Comment by hgflas** [comment]
that helps me a lot.

However, I updated AGL to version FF and now the folder _linux-raspbarrypi_ is no longer available. But there is a folder _"linux-raspberrypi-dev"_ in _meta-raspberrypi/recipes-kernel/Linux_ and the file _"linux-raspberrypi-dev.bb"_. Is it possible to configure  the kernel there as described above?

Is there also a way to check if the kernel configuration has been done? I have checked the /proc/config.gz File and the defined configuration isnt available there.

**Comment by rpcme** [comment]
Hello @hgflas does this remain an issue?  I apologize for getting back to you so late.  Note that we have a raspberry pi demo for the meta-aws bitbake metadata layer at https://github.com/aws-samples/meta-aws-demos

**Comment by rpcme** [comment]
Hello @hgflas - to support your first comment, the Greengrass recipe at https://github.com/aws/meta-aws.  Note that if you're on AGL Jumping Jellyfish then please use the Dunfell branch in that repo.  I will close this issue after three more days.
